"""initial schema: users, decks, cards

Matches what `db.create_all()` produced up to this point, so an existing database can be
brought under migration control with `flask db stamp 0001_initial_schema` instead of
being recreated.

Written by hand rather than autogenerated, and verified by the Migrations job in CI:
that job applies this against an empty Postgres and then runs `flask db check`, which
fails if the result differs from the models in any way.

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-09-21 02:30:00.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0001_initial_schema"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Created parents-first: decks references users, cards references decks.
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        # A named UNIQUE constraint, not a bare unique index -- app/models/user.py
        # depends on being able to recognise this in the IntegrityError from a duplicate
        # registration, to turn it into a 409 rather than a 500.
        sa.UniqueConstraint("email"),
    )
    # Note: users has no updated_at. User doesn't use TimestampMixin; only Deck and Card do.

    op.create_table(
        "decks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        # ON DELETE CASCADE is load-bearing: the relationships use passive_deletes=True,
        # so deleting a user relies on the database to remove their decks rather than
        # SQLAlchemy loading and deleting each row.
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_decks_user_id"), "decks", ["user_id"], unique=False)

    op.create_table(
        "cards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deck_id", sa.Integer(), nullable=False),
        sa.Column("front", sa.String(length=2000), nullable=False),
        sa.Column("back", sa.String(length=2000), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["deck_id"], ["decks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cards_deck_id"), "cards", ["deck_id"], unique=False)


def downgrade():
    # Children first, or the foreign keys block the drops.
    op.drop_index(op.f("ix_cards_deck_id"), table_name="cards")
    op.drop_table("cards")
    op.drop_index(op.f("ix_decks_user_id"), table_name="decks")
    op.drop_table("decks")
    op.drop_table("users")
